name: Claude Assistant
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: read

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
